### PR TITLE
filter by run in results by suites detail

### PR DESCRIPTION
**Pull request by klrmn**
the following tests are broken / missing:
- tests on the new methods in models.Suite (missing, coverage 94% on that file)
- 5 errors running tests inherited by tests.view.results.suites.test_views.SuiteResultsViewTest
- 3 tests i added but never fleshed out in tests.view.results.suites.test_views.SuiteResultsViewTest (failing)

so far, tests for views don't really make sense to me

### CODE REVIEW

**Comment by m8ttyB** [comment]
@klrmn is this still relevant?

@peterbe / @camd - got a moment for a review?

**Comment by klrmn** [comment]
no clue. given that almost 2 years have gone by, it's probably the thing to take the spirit without the code, rather than trying ot fix the merge conflicts.

**Comment by m8ttyB** [comment]
<3 thanks @klrmn -- I apologize for missing this [by 2 years] in the noise.

**Comment by peterbe** [comment]
It needs to be rebased against the current master. You're going to get a merge conflict to figure out.

**Comment by camd** [comment]
MozTrap EOL

**Pull request closed without merging**
