### PR TITLE
install lxml and defusedxml

### PR DESCRIPTION
**Pull request by peterbe**
@shinglyu r?

### CODE REVIEW

**Comment by shinglyu** [comment]
lxml needs to be compiled with the following lib packages (ubuntu): 

```
sudo apt-get install libxml2-dev libxslt1-dev 
```

If the staging & prod environment has it, then its an r+ for sure.

**Comment by peterbe** [comment]
@shinglyu the server is, sadly, not ubuntu. I'm sure the webops folks know how to install these because they're pretty standard compiled binaries.

**Comment by peterbe** [comment]
Hang on. This is wrong. `defusedxml` is not a binary package. It's pure python.

**Comment by peterbe** [comment]
@camd once we land this, do we just ask webops to install lxml for us?

**Comment by camd** [comment]
@peterbe I guess that's right.  I haven't tackled this type of thing before.  But maybe gozer could do that, yeah.

**Comment by shinglyu** [comment]
Yes, sorry for the confusion. We need the lxml binary, while the defusedxml is purely python.

**Comment by peterbe** [comment]
@shinglyu CC yourself onto https://bugzilla.mozilla.org/show_bug.cgi?id=1149331

**Comment by peterbe** [comment]
@shinglyu Also, please see [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1149331#c1)
When they have it installed on dev and stage, can you check that it works? Basically, be prepared to needinfo :)

**Comment by shinglyu** [comment]
Cool, thanks. I'll keep an eye on that.

**Pull request merged**
