### PR TITLE
Add a CaseVersionSearch API for search UI

### PR DESCRIPTION
**Pull request by shinglyu**
Add a case version serach API to mimic (and enhance) the MozTrap case search experience.

### CODE REVIEW

**Comment by peterbe** [comment]
@camd should maybe look at this one.

**Comment by camd** [comment]
@shinglyu : The code here looks great to me.  Would you be able to add a test for it, though?  Perhaps somewhere near here: https://github.com/mozilla/moztrap/blob/master/tests/model/library/api/test_caseversion_resource.py#L145-145.

It could be a new file, or in that file, as you feel appropriate.

Thanks again!

**Comment by shinglyu** [comment]
I've added the tests in the same file, because I think it is a variation of the `CaseVersionResource`. Thank you.

**Comment by shinglyu** [comment]
Hi @camd , can you give me some feedback on the test I added when you are available? Thanks.

**Comment by camd** [comment]
This looks great to me.  Thanks!

**Pull request merged**
